apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
type: Opaque
stringData:
    AMQP_URI: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: customers-secrets
type: Opaque
stringData:
    DB_URI: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-secrets
type: Opaque
stringData:
    DB_URI: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: products-secrets
type: Opaque
stringData:
    DB_URI: ""