openapi: 3.0.0

info:
  description: OpenAPI specification for the customers service
  version: 1.0.0
  title: Customers service OpenAPI contract

servers:
  - url: https://api.example.com/customers

paths:
  /:
    post:
      tags:
        - Customers
      summary: Creates a new customer
      requestBody:
        $ref: '#/components/requestBodies/CreateCustomer'
      responses:
        201:
          description: Returns the new customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerProperties'
        500:
          description: Error creating customer
    put:
      tags:
        - Customers
      summary: Updates an existing customer based on the received data
      responses:
        200:
          description: Returns updated customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerProperties'
        404:
          description: Customer not found
  /{email}:
    parameters:
      - $ref: '#/components/parameters/email'
    get:
      tags:
        - Customers
      summary: Fetches a customer
      responses:
        200:
          description: Returns existing customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerProperties'
        404: 
          description: Customer not found
    delete:
      tags:
        - Customers
      summary: Deletes a customer
      responses:
        204:
          description: Customer deleted successfully
        404:
          description: Customer not found
   
components:
  parameters:
    email:
      name: email
      description: Customer email
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/CustomerProperties/properties/email'
  requestBodies:
    CreateCustomer:
      description: Create a new customer
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                description: Customer name
                type: string
              email:
                description: Customer email
                type: string
              phone:
                description: Customer phone
                type: integer
                format: int32
              billing_address:
                description: Customer billing address
                type: string
              shipping_address:
                description: Customer shipping address
                type: string
              credit_standing:
                description: Current credit balance of the customer
                type: number
                format: float
            required:
              - name
              - email
              - billing_address
              - shipping_address
  schemas:
    CustomerProperties:
      type: object
      description: Customer entity properties
      properties:
        customer_id:
          description: Customer ID
          type: integer
          format: int32
        name:
          description: Customer name
          type: string
        email:
          description: Customer email
          type: string
        phone:
          description: Customer phone
          type: integer
          format: int32
        billing_address:
          description: Customer billing address
          type: string
        shipping_address:
          description: Customer shipping address
          type: string
        credit_standing:
          description: Current credit balance of the customer
          type: number
          format: float
      required:
        - name
        - email
        - billing_address
        - shipping_address
