openapi: 3.0.0

info:
  description: OpenAPI specification for the products service
  version: 1.0.0
  title: Products service OpenAPI contract

servers:
  - url: https://api.example.com/products

paths:
  /:
    post:
      summary: Creates a new product
      tags:
        - Products
      requestBody:
        $ref: '#/components/requestBodies/CreateProduct'
      responses:
        201:
          description: Returns the new product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductProperties'
        500:
          description: Error creating product
    put:
      tags:
        - Products
      summary: Updates an existing product based on the received data
      responses:
        202:
          description: Returns updated product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductProperties'
        404:
          description: Product not found
  /{product_id}:
    parameters:
      - $ref: '#/components/parameters/product_id'
    get:
      tags:
        - Products
      summary: Fetches a product
      responses:
        200:
          description: Returns existing product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductProperties'
        404: 
          description: Product not found
    delete:
      tags:
        - Products
      summary: Deletes a product
      responses:
        204:
          description: Product deleted successfully
        404:
          description: Product not found
  
components:
  parameters:
    product_id:
      name: product_id
      description: Product ID
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/id'
  requestBodies:
    CreateProduct:
      description: Create a new product
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductProperties'
  schemas:
    ProductProperties:
      description: Product entity properties
      type: object
      properties:
        product_id:
          $ref: '#/components/schemas/id'
        name:
          description: Product name
          type: string
        price:
          description: Product price
          type: number
          format: float
        category:
          description: Product category
          type: string
        stock_items:
          description: Product available stock
          type: integer
          format: int32
        reserved_items:
          description: Product reserved stock (orders in process of being accepted)
          type: integer
          format: int32
      required:
        - name
        - price
    id:
      description: Reusable ID property schema
      type: integer
      format: int32
