swagger: "2.0"

info:
  title: "Order API"
  version: "1.0"

basePath: /v1.0

paths:
  /:
    get:
      responses:
        '200':
          description: 'Fetch an order by its ID'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'

definitions:
  Order:
    type: object
    properties:
      id:
        type: integer
      name: { type: string }